ch18/pizzeria/pizzas/urls.py
"""Defines URL patterns for pizzas."""

from django.urls import path
from . import views

urlpatterns = [
    # Home Page
    path('', views.index, name='index'),
    path('pizzas/', views.pizzas, name='pizzas'),
    path('pizzas/(?P<pizza_id>\d+)/', views.pizza, name='pizza'),
]

ch18/pizzeria/pizzeria/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include(('pizzas.urls', 'pizzas'), 
        namespace='pizzas')),
]

ch18/pizzeria/pizzas/models.py
from django.db import models

class Pizza(models.Model):
    """An individual pizza."""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string represenation of the pizza."""
        if len(self.name) < 50:
            return self.name
        else:
            return self.name[:50] + "..."

class Topping(models.Model):
    """An individual topping."""
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """ Return a string represenation of the topping."""
        if len(self.name) < 50:
            return self.name
        else:
            return self.name[:50] + "..."

ch18/pizzeria/pizzas/views.py
from django.shortcuts import render

from .models import Pizza, Topping

def index(request):
    """The home page for pizzas"""
    return render(request, 'pizzas/index.html')

def pizzas(request):
    """Show all pizzas"""
    pizzas = Pizza.objects.order_by('date_added')
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    """Show a single pizza and its toppings."""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('-date_added')
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)
    

ch18/pizzeria/pizzas/templates/pizzas/base.html
<p>
  <a href="{% url 'pizzas:index' %}">Pizzeria</a> - 
  <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
</p>

{% block content %}{% endblock content %}

ch18/pizzeria/pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}
<p>This is the homepage for a test project about pizzas.</p>
{% endblock content %}

ch18/pizzeria/pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}

{% block content %}

<p>Pizza: {{ pizza }}</p>

<p>Toppings:</p>
<ul>
{% for topping in toppings %}
  <li>
    <p>{{ topping.name }}</p>
  </li>
{% empty %}
  <li>
      There are no topping for this pizza yet.
  </li>
{% endfor %}

</ul>

{% endblock content %}

ch18/pizzeria/pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}

<p>Pizzas</p>

<ul>
{% for pizza in pizzas %}
  <li>
    <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
  </li>
{% empty %}
  <li>No pizzas have been added yet.</li>
{% endfor %}
</ul>

{% endblock content %}